package com.peterchege.blogger.util

object Screens {
    const val LOGIN_SCREEN = "LOGIN_SCREEN"
    const val SIGNUP_SCREEN = "SIGNUP_SCREEN"
    const val DASHBOARD_SCREEN = "DASHBOARD_SCREEN"


    const val HOME_SCREEN = "HOME_SCREEN"
    const val SAVED_POST_SCREEN = "SAVED_POST_SCREEN"
    const val NOTIFICATION_SCREEN = "NOTIFICATION_SCREEN"

    const val ADD_NEW_POST_SCREEN = "ADD_NEW_POST_SCREEN"
    const val POST_SCREEN = "POST_SCREEN"
    const val FEED_SCREEN = "FEED_SCREEN"
    const val DRAFT_SCREEN = "DRAFT_SCREEN"
    const val UPDATE_POST_SCREEN = "UPDATE_POST_SCREEN"
    const val ADD_NEW_POST_NAVIGATION = "ADD_NEW_POST_NAVIGATION"

    const val PROFILE_NAVIGATION = "PROFILE_NAVIGATION"
    const val PROFILE_SCREEN = "PROFILE_SCREEN"
    const val PROFILE_FOLLOWER_FOLLOWING_SCREEN = "PROFILE_FOLLOWER_FOLLOWING_SCREEN"

    const val AUTHOR_PROFILE_NAVIGATION = "AUTHOR_PROFILE_NAVIGATION"
    const val AUTHOR_FOLLOWER_FOLLOWING_SCREEN = "AUTHOR_FOLLOWER_FOLLOWING_SCREEN"
    const val AUTHOR_PROFILE_SCREEN = "AUTHOR_PROFILE_SCREEN"
    const val CATEGORY_SCREEN = "CATEGORY_SCREEN"
}