# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "My awesome app"
      lane :distribute do

          build_android_app(
            task: "clean assemble",
            build_type: "Debug"
          )
          # build_android_app is a built-in fastlane action.
          firebase_app_distribution(
              app: "1:365193487318:android:7809e25308aaf21fd47a77",
              release_notes: "Lots of amazing new features to test out!",
              groups:"trusted-testers",
              android_artifact_type:"APK",
              debug:true,
              firebase_cli_token:"1//031gtnPQJBCtpCgYIARAAGAMSNwF-L9Irj2eO8cqb7v5EiCCxIMWSr4YfGttLCD4R47u05mxXZcctLw6zdf5r3ytXBK1l_AhZRlI",
              service_credentials_file:"C:/Users/User/AndroidStudioProjects/Blogger/fastlane/firebase_distribution_key.json",
              testers_file:"C:/Users/User/AndroidStudioProjects/Blogger/fastlane/testers.txt",
          )
      end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
